---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-from-main-site
  labels:
    app: example-base-deployment
spec:
  selector:
    matchLabels:
      app: example-base-deployment
      tier: flux-system
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: example-base-deployment
        tier: flux-system
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: BASE_VALUE
          value: "1"
