apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-agent-conf
  namespace: observability
  labels:
    app: opentelemetry
    component: adot-agent-conf
data:
  adot-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: "otel-collector.observability.svc.cluster.local:55680"
        insecure: true
    processors:
      resource:
        attributes:
          - key: pod_name
            value: ${POD_NAME} 
            action: insert
      batch:
      memory_limiter:
        ballast_size_mib: 500
        limit_percentage: 70
        spike_limit_percentage: 30
        check_interval: 5s
      queued_retry:
        num_workers: 4
        queue_size: 100
        retry_on_failure: true
    extensions:
      health_check: {}
      zpages: {}
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource, batch, queued_retry]
          exporters: [otlp]