apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-conf
  namespace: observability
  labels:
    app: opentelemetry
    component: adot-collector-conf
data:
  adot-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
      queued_retry:
    extensions:
      health_check: {}
      zpages: {}
    exporters:
      awsxray:
          region: 'eu-west-1'
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces/2:
          receivers: [otlp]
          processors: [batch, queued_retry]
          exporters: [awsxray]